New dotfiles and bin
Signed-off-by: Osamu Aoki <osamu@debian.org>

diff --git a/halexec/deb b/halexec/deb
--- a/halexec/deb
+++ b/halexec/deb
@@ -3,7 +3,7 @@
 # Copyright 2020 Osamu Aoki <osamu@debian.org>, GPL-2+
 # vim: set ts=2 sts=2 sw=2 ai et:
 #############################################################################
-__term_exit () {
+__term_exit() {
   echo
   echo "E: Process externally interrupted.  Terminating."
   echo
@@ -11,16 +11,16 @@ __term_exit () {
 }
 trap '__term_exit' HUP INT QUIT TERM
 # dash: EXIT (but no ERR)
-__err_exit () {
+__err_exit() {
   echo
   echo "E: Internal process returned an error exit.  Terminating."
   echo "   Probably, ~/.debrc contain non-existing package etc..."
   echo
   exit 1
 }
-__exit_exit () {
+__exit_exit() {
   #echo
-	#echo "Have a nice day :-)"
+  #echo "Have a nice day :-)"
   #echo
   exit 0
 }
@@ -50,94 +50,94 @@ PACKAGE_X="-e s/@KBF@//"
 PACKAGE_T="-e s/@GUI@//"
 PACKAGE_U="-e s/@JPN@//"
 while [ -n "$1" ]; do
-	case "$1" in
-		'-s'|'--simulate')
-      echo "... Simulation ... no actual install"
-      OPTS="-s"
-			shift
-			continue
-		;;
-		'-c'|'--check')
-      echo "... Check ... no actual install"
-      MODE="check"
-			shift
-			continue
+  case "$1" in
+  '-s' | '--simulate')
+    echo "... Simulation ... no actual install"
+    OPTS="-s"
+    shift
+    continue
     ;;
-		'-x'|'--exclude-kernel')
-      PACKAGE_X=""
-			shift
-			continue
+  '-c' | '--check')
+    echo "... Check ... no actual install"
+    MODE="check"
+    shift
+    continue
     ;;
-		'-t'|'--tui')
-      PACKAGE_T=""
-			shift
-			continue
+  '-x' | '--exclude-kernel')
+    PACKAGE_X=""
+    shift
+    continue
     ;;
-		'-u'|'--us')
-      PACKAGE_U=""
-			shift
-			continue
+  '-t' | '--tui')
+    PACKAGE_T=""
+    shift
+    continue
     ;;
-		'-h'|'--help')
-      fn_help
-			exit 0
-		;;
-		'--')
-      shift
-      break
-		;;
-		*)
-      break
-		;;
-	esac
+  '-u' | '--us')
+    PACKAGE_U=""
+    shift
+    continue
+    ;;
+  '-h' | '--help')
+    fn_help
+    exit 0
+    ;;
+  '--')
+    shift
+    break
+    ;;
+  *)
+    break
+    ;;
+  esac
 done
 
 #############################################################################
 PACKAGE_FILTER="$PACKAGE_X $PACKAGE_T $PACKAGE_U"
 
 while [ -n "$1" ]; do
-	case "$1" in
-		r*|R*|0)
-      PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@//"
-			shift
-			continue
+  case "$1" in
+  r* | R* | 0)
+    PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@//"
+    shift
+    continue
     ;;
-		m*|M*|1)
-      PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@//"
-			shift
-			continue
+  m* | M* | 1)
+    PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@//"
+    shift
+    continue
     ;;
-		w*|W*|2)
-      PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@// -e s/@WKS@//"
-			shift
-			continue
+  w* | W* | 2)
+    PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@// -e s/@WKS@//"
+    shift
+    continue
     ;;
-		p*|P*|3)
-      PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@// -e s/@WKS@// -e s/@PRG@//"
-			shift
-			continue
+  p* | P* | 3)
+    PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@// -e s/@WKS@// -e s/@PRG@//"
+    shift
+    continue
     ;;
-		d*|D*|4)
-      PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@// -e s/@WKS@// -e s/@PRG@// -e s/@DOC@//"
-			shift
-			continue
+  d* | D* | 4)
+    PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@// -e s/@WKS@// -e s/@PRG@// -e s/@DOC@//"
+    shift
+    continue
     ;;
-		e*|E*|5)
-      PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@// -e s/@WKS@// -e s/@PRG@// -e s/@DOC@// -e s/@EXT@//"
-			shift
-			continue
+  e* | E* | 5)
+    PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@// -e s/@WKS@// -e s/@PRG@// -e s/@DOC@// -e s/@EXT@//"
+    shift
+    continue
     ;;
-		f*|F*|6)
-      PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@// -e s/@WKS@// -e s/@PRG@// -e s/@DOC@// -e s/@EXT@// -e s/@FUL@//"
-			shift
-			continue
+  f* | F* | 6)
+    PACKAGE_FILTER="$PACKAGE_FILTER -e s/@RFS@// -e s/@MIN@// -e s/@WKS@// -e s/@PRG@// -e s/@DOC@// -e s/@EXT@// -e s/@FUL@//"
+    shift
+    continue
     ;;
-		*)
-			echo "Internal error! with '$1'" >&2
-      help
-			exit 1
-		;;
-	esac
+  *)
+    echo "Internal error! with '$1'" >&2
+    help
+    exit 1
+    ;;
+  esac
 done
 
 #############################################################################
@@ -158,9 +158,13 @@ PACKAGES="$($PACKAGE_FILTER <~/.debrc | xargs -n1)"
 #echo $PACKAGES
 if [ "$MODE" = "check" ]; then
   echo "-----------------------------------------------------------------------"
-  aptitude search '~i!~prequired!~pimportant!~pstandard!~M' | sed -e 's/^i  //g' -e 's/^ih /*HOLD* /g'|\
-  grep -v "$(echo -n '^\(';echo -n "$PACKAGES" | sed -e 's/$/ - \\|/g' | tr -d '\n';echo -n 'XXX_NON_EXISTING_PACKAGE_XXX\)')"|\
-  sort
+  aptitude search '~i!~prequired!~pimportant!~pstandard!~M' | sed -e 's/^i  //g' -e 's/^ih /*HOLD* /g' |
+    grep -v "$(
+      echo -n '^\('
+      echo -n "$PACKAGES" | sed -e 's/$/ - \\|/g' | tr -d '\n'
+      echo -n 'XXX_NON_EXISTING_PACKAGE_XXX\)'
+    )" |
+    sort
   echo "-----------------------------------------------------------------------"
   exit 0
 else
