improve exit trap
Signed-off-by: Osamu Aoki <osamu@debian.org>

diff --git a/halexec/install b/halexec/install
--- a/halexec/install
+++ b/halexec/install
@@ -1,8 +1,30 @@
-#!/bin/bash -e
+#!/bin/sh -e
 ## @brief install or check packages using ~/.debrc
 # Copyright 2020 Osamu Aoki <osamu@debian.org>, GPL-2+
 # vim: set ts=2 sts=2 sw=2 ai et:
 #############################################################################
+__term_exit () {
+  echo
+  echo "E: Process externally interrupted.  Terminating."
+  echo
+  exit 1
+}
+trap '__term_exit' HUP INT QUIT TERM
+# dash: EXIT (but no ERR)
+__err_exit () {
+  echo
+  echo "E: Internal process returned an error exit.  Terminating."
+  echo "   Probably, ~/.debrc contain non-existing package etc..."
+  echo
+  exit 1
+}
+__exit_exit () {
+  echo
+	echo "Have a nice day :-)"
+  echo
+  exit 0
+}
+trap '[ $? -eq 0 ] && __exit_exit || __err_exit' EXIT
 PACKAGE_LEVEL=0
 MODE="install"
 OPTS=""
@@ -19,9 +41,9 @@ fn_help() {
 TEMP=$(getopt -o 'sch123456' --long 'simulate,check,help' -n 'install' -- "$@")
 
 if [ $? -ne 0 ]; then
-	echo 'Terminating...' >&2
+  echo 'Terminating...' >&2
   fn_help
-	exit 1
+  exit 1
 fi
 
 # Note the quotes around "$TEMP": they are essential!
