schroot-shell
Signed-off-by: Osamu Aoki <osamu@debian.org>

diff --git a/schroot-shell b/schroot-shell
--- a/schroot-shell
+++ b/schroot-shell
@@ -3,63 +3,88 @@
 # A convenience script to use schroot desktop profile
 # You can run 'gitk' with this.
 
-if [ "$(id -u)" != 0 ] && type xhost >/dev/null; then
-  XHOST="xhost"
-else
-  XHOST=":"
-fi
-# For ease of customization, here are key parameters
-SCHROOT_SHELL="$0"
-USERNAME="$(id -u -n)"
-TYPE="${TYPE:-source}"
-SCHROOT_PROFILE="${SCHROOT_PROFILE:-desktop}"
-ARCH="${ARCH:-amd64}"
-BASECHROOT="/srv/chroot" # enough disk space here
-SCHROOT_PROFILE="${SCHROOT_PROFILE:-desktop}" # customize /etc/schroot/chroot.d/desktop
-URL="http://127.0.0.1:3142/deb.debian.org/debian"
 _help() {
-  echo "NAME"
-  echo "    ${0##*/} - start a shell in chroot with current home data."
-  echo
-  echo "SYNOPSIS"
-  echo "    ${0##*/} [|--init|--prep|--upgrade] [DIST]"
-  echo
-  echo "DESCRIPTION"
-  echo "    This helps you to work with persistent pre-loaded (source) chroot"
-  echo "    environment and is modeled after *sbuild-shell* and *sbuild-update*"
-  echo "    but uses an independent chroot which is not used by sbuild."
-  echo
-  echo "    This uses schroot profile '${SCHROOT_PROFILE}'.  You must customize this"
-  echo "    profile at '/etc/schroot/${SCHROOT_PROFILE}/fstab' to list all mounted"
-  echo "    devices in your home directory.  The actual profile used can be"
-  echo "    changed by setting the '\${SCHROOT_PROFILE}' environment variable."
-  echo
-  echo "    This normally starts persistent (source) chroot environment for the"
-  echo "    DIST distribution and provides a shell prompt in the current console"
-  echo "    terminal with access to the data in your home directory."
-  echo "    This is modeled after *sbuild-shell*."
-  echo
-  echo "    If DIST is unset, '\${DIST}' environment variable is used instead."
-  echo "    If '\${DIST}' environment variable is also unset, 'unstable' is used."
-  echo
-  echo "    DIST can be 'unstable', 'testing', 'stable', 'oldstable', or"
-  echo "    'oldoldstable'; and can be shortened as 'u', 't', 's', 'o', or 'oo'."
-  echo
-  echo "    If '--init' or '-i' is given as an option, this initializes schroot"
-  echo "    environment for this command and optionally for sbuild."
-  echo "      * '/srv/chroot/\${DIST}-amd64-sbuild' used by sbuild as a minimum system."
-  echo "      * '/srv/chroot/\${DIST}-amd64-${SCHROOT_PROFILE}' used by this program to"
-  echo "        start the terminal shell prompt as a source chroot of a loaded system."
-  echo "    This is a wrapper around *sbuild-createchroot*."
-  echo
-  echo "    If '--prep' or '-p' is given as an option, this updates schroot"
-  echo "    environment with basic extra packages normally needed for the console"
-  echo "    terminal operations to '/srv/chroot/\${DIST}-amd64-${SCHROOT_PROFILE}'"
-  echo
-  echo "    If '--upgrade' or '-u' is given as an option, this updates schroot"
-  echo "    environment of '/srv/chroot/\${DIST}-amd64-${SCHROOT_PROFILE}'"
-  echo "    This is modeled after *sbuild-update*."
-  echo
+cat << EOF
+NAME
+    ${0##*/} - start a shell in chroot with current home data.
+
+SYNOPSIS
+    ${0##*/} [DIST [CONFIG]]
+    ${0##*/} --config [CONFIG]
+    ${0##*/} [--init|--prep|--upgrade] [DIST [CONFIG]]
+
+DESCRIPTION
+
+This wrapper command of *schroot* offers a set of helper commands to work in
+the persistent pre-loaded (source) chroot system environment while sharing the
+user data from the user's home directory of the host system.
+
+Here, if 'CONFIG' and 'DIST' are missing in the command line, 'desktop' for
+'CONFIG' and 'unstable' for 'DIST' are used as the default values.
+
+The *${0##*/}* command is normally invoked as:
+
+   ${0##*/} [DIST [CONFIG]]
+
+This starts an interactive shell in the 'DIST-${ARCH}-CONFIG' source chroot
+managed by the *schroot* command while bind mounting the user data from the
+user's home directory of the host system.  This is somewhat modeled after
+*sbuild-shell*.  While *sbuild-shell* is designed to work with the session
+chroot and the changes made from *sbuild-shell* to the chroot is discarded,
+the changes made from *${0##*/}* to the chroot is persistent.
+
+In order for the *${0##*/}* command to function, you need to set up the
+'DIST-${ARCH}-CONFIG' source chroot properly.
+
+The 'DIST-${ARCH}-CONFIG' source chroot can be initialized in 3
+steps.
+
+  1. Create the setup script configuration files for *schroot* under
+     '/etc/schroot/CONFIG/' as explained in the 'FILES' section under 'Setup
+     script configuration' in schroot.conf(5) for '/etc/schroot/default'.
+
+       ${0##*/} --config [CONFIG]
+
+  2. Customize the setup script configuration files for *schroot* at
+     '/etc/schroot/CONFIG/fstab' to list all mounted devices in your home
+     directory.
+
+  3. Create a chroot file system for 'DIST' at
+     '/srv/chroot/DIST-${ARCH}-CONFIG' using the setup script configuration
+     files in '/etc/schroot/CONFIG'.
+
+       ${0##*/} --init [DIST [CONFIG]]
+
+    Here, 'DIST' specifies base distribution of the chroot system.  'DIST'
+    can be 'unstable' (default), 'testing', 'stable', 'oldstable', or
+    'oldoldstable'.  These can be shortened as 'u', 't', 's', 'o', or 'oo'
+    in the command line.
+
+The 'DIST-${ARCH}-CONFIG' source chroot can be updated to the latest
+state by:
+
+   ${0##*/} --update [DIST [CONFIG]]
+
+The 'DIST-${ARCH}-CONFIG' source chroot can be prepped up with a few
+pre-defined extra packages desirable for the shell activities by:
+
+   ${0##*/} --prep [DIST [CONFIG]]
+
+For 'CONFIG', values 'default', 'minimal', 'buildd', and 'sbuild'
+should be avoided unless you know what exactly happens since these setup
+scripts are already used by *sbuild* and *schroot*.
+
+The *${0##*/}* command offers a generarized and similar functionality of
+*sbuild-createchroot*, *sbuild-update*, and *sbuild-shell* for the persistent
+chroot shell environment.  The *${0##*/}* command automatically becomes root
+when needed.
+
+Parametrs:
+  TYPE    = '$TYPE'
+  DIST    = '$DIST'
+  ARCH    = '$ARCH'
+  CONFIG  = '$CONFIG'
+EOF
 }
 
 _noxhost () {
@@ -71,178 +96,299 @@ _noxhost () {
 
 _distsh () {
   $XHOST -
-  echo "I: use ${TYPE}:${DIST}-${ARCH}-${SCHROOT_PROFILE}"
+  echo
+  echo "I: execute in ${TYPE}:${DIST}-${ARCH}-${CONFIG}"
+  echo " % $*"
   $XHOST "+si:localuser:$USERNAME"
   echo "I: allow xhost only for the localuser"
-  schroot -c "${TYPE}:${DIST}-${ARCH}-${SCHROOT_PROFILE}"
+  # COMMAND=$SHELL -i
+  schroot -c "${TYPE}:${DIST}-${ARCH}-${CONFIG}" -- "$@"
   echo "I: normal exit from schroot"
 }
 
 _su () {
   if [ "$(id -u)" != 0 ]; then
     echo "I: execute as root: $*"
-    exec sudo --preserve-env=DIST,SCHROOT_PROFILE "$@"
+    exec sudo "$@"
   fi
 }
-_init () {
-  echo "I: executing as '$(id -u -n)' ..."
+
+_config () {
+  echo "I: Setting up $CONFIG"
+  if [ -d "/etc/schroot/$CONFIG" ]; then
+    echo "E: /etc/schroot/$CONFIG already exists."
+    exit 1
+  fi
+  mkdir -p "/etc/schroot/$CONFIG"
+  cat > "/etc/schroot/$CONFIG/copyfiles" <<EOF
+# Files to copy into the chroot from the host system.
+#
+# <source and destination>
+/etc/resolv.conf
+EOF
+  cat > "/etc/schroot/$CONFIG/fstab" <<EOF
+# fstab: static file system information for chroots.
+# Note that the mount point will be prefixed by the chroot path
+# (CHROOT_PATH)
+#
+# <file system> <mount point>   <type>  <options>       <dump>  <pass>
+# I/O device
+/proc           /proc           none    rw,bind         0       0
+/sys            /sys            none    rw,bind         0       0
+/dev            /dev            none    rw,bind         0       0
+/dev/pts        /dev/pts        none    rw,bind         0       0
+# user data
+/root           /root           none    rw,bind         0       0
+/home           /home           none    rw,bind         0       0
+$USERHOME       $USERHOME       none    rw,bind         0       0
+# Adjust for installation
+#$USERHOME/Downloads  $USERHOME/Downloads none    rw,bind         0       0
+#$USERHOME/github     $USERHOME/github    none    rw,bind         0       0
+#$USERHOME/salsa      $USERHOME/salsa     none    rw,bind         0       0
+#$USERHOME/tmp        $USERHOME/tmp       none    rw,bind         0       0
+
+# Runtime user data
+# ?
+/tmp            /tmp            none    rw,bind         0       0
+# If you use gdm3, uncomment this line to allow Xauth to work
+/var/run/gdm3   /var/run/gdm3   none    rw,bind         0       0
+# For PulseAudio and other desktop-related things
+/var/lib/dbus   /var/lib/dbus  none    rw,bind         0       0
+# For wayland on systemd ... maybe XXX FIXME XXX needs testing
+/run/user/1000 /run/user/1000 none    rw,bind         0       0
+# It may be desirable to have access to /run, especially if you wish
+# to run additional services in the chroot.  However, note that this
+# may potentially cause undesirable behaviour on upgrades, such as
+# killing services on the host.
+#/run           /run            none    rw,bind         0       0
+#/run/lock      /run/lock       none    rw,bind         0       0
+#/dev/shm       /dev/shm        none    rw,bind         0       0
+#/run/shm       /run/shm        none    rw,bind         0       0
+EOF
+  cat > "/etc/schroot/$CONFIG/nssdatabases" <<EOF
+# System databases to copy into the chroot from the host system.
+#
+# <database name>
+passwd
+shadow
+group
+gshadow
+services
+protocols
+networks
+hosts
+EOF
+}
+
+_init_sbuild () {
   # create a minimum schroot for sbuild
-  echo "I: setting up DIST=${DIST} for sbuild ..."
-  DIRSCHROOT="${BASECHROOT}/${DIST}-${ARCH}-sbuild"
-  if [ ! -e "${DIRSCHROOT}" ]; then
-    sbuild-createchroot --include=eatmydata,ccache  "${DIST}" "${DIRSCHROOT}" "${URL}"
+  echo "I: setting up DIST=${DIST} for sbuild chroot."
+  SBUILD_CHROOT="${BASECHROOT}/${DIST}-${ARCH}-sbuild"
+  if [ -e "${SBUILD_CHROOT}" ]; then
+    echo "I: ${SBUILD_CHROOT} exists, so use it as the starting point."
   else
-    echo "W: ${DIRSCHROOT} exists so use it"
+    DEBURL="http://deb.debian.org/debian"
+    sbuild-createchroot --include=eatmydata,ccache  "${DIST}" "${SBUILD_CHROOT}" "${DEBURL}"
   fi
-  # create additional chroot for use by terminal and X (No wayland?)
-  # $ xhost +si:localuser:<username> ; schroot -c chroot:${DIRTERM}-?? ; xhost -
-  echo "I: setting up DIST=${DIST} for ${SCHROOT_PROFILE} ..."
-  DIRTERM="${BASECHROOT}/${DIST}-${ARCH}-${SCHROOT_PROFILE}"
-  if [ ! -e "${DIRTERM}" ]; then
-    cp -a --reflink=always  "${DIRSCHROOT}"  "${DIRTERM}"
+}
+
+_init () {
+  echo "I: _init ${DIST}-${ARCH}-${CONFIG}"
+  _init_sbuild
+  # create additional chroot for use by terminal and X (Yes: xwayland, No: pure wayland)
+  # $ xhost +si:localuser:<username> ; schroot -c chroot:${DESKTOP_CHROOT}-?? ; xhost -
+  echo "I: setting up DIST=${DIST} for ${CONFIG} ..."
+  DESKTOP_CHROOT="${BASECHROOT}/${DIST}-${ARCH}-${CONFIG}"
+  if [ ! -e "${DESKTOP_CHROOT}" ]; then
+    cp -a --reflink=always  "${SBUILD_CHROOT}"  "${DESKTOP_CHROOT}"
   else
-    echo "W: ${DIRTERM} exists so use it"
+    echo "I: chroot ${DESKTOP_CHROOT} already exists, so use it as is."
+    exit 0
   fi
-  # create schroot data entry /etc/schroot/chroot.d/${DIST}-${ARCH}-${SCHROOT_PROFILE}
-  # while using schroot $SCHROOT_PROFILE with uniq filename
+  # create schroot data entry /etc/schroot/chroot.d/${DIST}-${ARCH}-${CONFIG}
+  # while using schroot $CONFIG with uniq filename
   # shellcheck disable=SC2086
-  SCHROOTCONF="$(ls -1 /etc/schroot/chroot.d/${DIST}-${ARCH}-${SCHROOT_PROFILE}-* 2>/dev/null)"
-  if [ -z "$SCHROOTCONF" ]; then
+  CONF_SCHROOT="$(ls -1 /etc/schroot/chroot.d/${DIST}-${ARCH}-${CONFIG}-* 2>/dev/null || true)"
+  if [ -z "$CONF_SCHROOT" ]; then
     if [ "${DIST}" = unstable ]; then
-      ALIASES_LINE="aliases=sid-${ARCH}-${SCHROOT_PROFILE},sid-${SCHROOT_PROFILE},${SCHROOT_PROFILE}"
+      ALIASES_LINE="aliases=sid-${ARCH}-${CONFIG},sid-${CONFIG},${CONFIG}"
     else
       ALIASES_LINE="#aliases=<please add your alias here and uncomment>"
     fi
-    cat > "/etc/schroot/chroot.d/${DIST}-${ARCH}-${SCHROOT_PROFILE}-$$" <<EOF
-[${DIST}-${ARCH}-${SCHROOT_PROFILE}]
-description=Debian ${DIST} ${ARCH} chroot for terminal with shared data
+    CONF_SCHROOT="/etc/schroot/chroot.d/${DIST}-${ARCH}-${CONFIG}-$$"
+    cat > "$CONF_SCHROOT" <<EOF
+[${DIST}-${ARCH}-${CONFIG}]
+description=Debian ${DIST} ${ARCH} chroot with shared desktop data
 groups=root,sbuild
 root-groups=root,sbuild
 source-groups=root,sbuild
 source-root-groups=root,sbuild
-profile=${SCHROOT_PROFILE}
+profile=${CONFIG}
 type=directory
 preserve-environment=true
-directory=/srv/chroot/${DIST}-${ARCH}-${SCHROOT_PROFILE}
+directory=/srv/chroot/${DIST}-${ARCH}-${CONFIG}
 union-type=overlay
 command-prefix=eatmydata
 ${ALIASES_LINE}
 EOF
+    echo "I: ${CONF_SCHROOT} created"
   else
-    echo "W: ${SCHROOTCONF} exists so use it"
+    echo "I: ${CONF_SCHROOT} already exists so use it"
   fi
 }
 
 _upgrade () {
-  cat <<EOF | "$SCHROOT_SHELL" "$DIST"
+echo "I: _upgrade ${DIST}-${ARCH}-${CONFIG}"
 # -udcar
-apt-get update --yes
-apt-get dist-upgrade --yes
-apt-get clean --yes
-apt-get autoclean --yes
-apt-get autoremove --yes
-EOF
+_distsh apt-get update --yes
+_distsh apt-get dist-upgrade --yes
+_distsh apt-get clean --yes
+_distsh apt-get autoclean --yes
+_distsh apt-get autoremove --yes
 }
 
-# x11-xserver-util package is needed by xhost command
-# xhost command is needed by gitk operation
+_aptget () {
+  _distsh apt-get install --yes "$@"
+}
+
 _prep () {
-  cat <<EOF | $SCHROOT_SHELL "$DIST"
-if apt-get install --yes aptitude mc vim nano- devscripts gitk git sudo \
-    locales-all imediff fzf rlwrap eatmydata ccache x11-xserver-utils ; then
-  echo "I: Adding pre-loaded packages"
-elif apt-get install --yes aptitude mc vim nano- devscripts gitk git sudo \
-    locales-all rlwrap eatmydata ccache x11-xserver-utils ; then
-  echo "I: Adding pre-loaded packages (missing: imediff fzf)"
-else
-  echo "E: Failed to add pre-loaded packages."
-  echo "   Please resolve manually by logging into $DIST and execute."
-  echo
-  echo "   $ sudo dpkg --configure -a"
-  echo
-  exit 1
-fi
-EOF
+  echo "I: _prep ${DIST}-${ARCH}-${CONFIG}"
+  # Install piece-by-piece to help understand the unstable breakage situation
+  _aptget sudo x11-xserver-utils
+  _aptget locales-all
+  _aptget aptitude mc vim nano-
+  _aptget git gitk
+  _aptget imediff fzf rlwrap
+  _aptget eatmydata ccache
+  # netbase conflict with /etc/services
+  _aptget netbase
+  _aptget devscripts
+  # x11-xserver-util package is needed by xhost command
+  # xhost command is needed by gitk operation
 }
 
 #############################################################################
-DIST="${DIST:-unstable}"
-SCHROOT_CMD="shell"
+THIS_COMMAND="$0"
+echo
+echo "I: executing as USER='$(id -u -n)'"
+echo " % $*"
+if [ "$(id -u)" != 0 ] && type xhost >/dev/null; then
+  XHOST="xhost"
+else
+  XHOST=":"
+fi
+# For ease of customization, here are key parameters
+USERNAME="$(id -u -n)"
+USERHOME="/home/$USERNAME"
+BASECHROOT="/srv/chroot" # enough disk space here
+TYPE="source" # chroot namespace
+ARCH="amd64"  # adjust for system
 
-while [ -n "$1" ]; do
-  case "$1" in
-    -i|--in*)
-      SCHROOT_CMD="init"
-      ;;
-    -p|--pr*)
-      SCHROOT_CMD="prep"
-      ;;
-    -u|--up*)
-      SCHROOT_CMD="upgrade"
-      ;;
-    u)
-      DIST="unstable"
-      break
-      ;;
-    t)
-      DIST="testing"
-      break
-      ;;
-    s)
-      DIST="stable"
-      break
-      ;;
-    o)
-      DIST="oldstable"
-      break
-      ;;
-    oo)
-      DIST="oldoldstable"
-      break
-      ;;
-    unstable|testing|stable|oldstable|oldoldstable|sid|bookworm|bullseye|buster|strech)
-      DIST="${1}"
-      break
-      ;;
-    -h|--help)
-      _help
-      exit 0
-      ;;
-    *)
-      echo "W: unknown distribution ${1}"
-      _help
-      exit 0
-      ;;
-  esac
-  shift
-done
+COMMAND_MODE="shell"
+case "$1" in
+  -c|--co*)
+    COMMAND_MODE="config"
+    shift
+    ;;
+  -i|--in*)
+    COMMAND_MODE="init"
+    shift
+    ;;
+  -p|--pr*)
+    COMMAND_MODE="prep"
+    shift
+    ;;
+  -u|--up*)
+    COMMAND_MODE="upgrade"
+    shift
+    ;;
+  -h|--help)
+    _help
+    exit 0
+    ;;
+  -*)
+    echo "WOW -h not found"
+    _help
+    exit 0
+    ;;
+  '#')
+    echo "WOW # found"
+    exit 0
+    ;;
+esac
 
-#echo "I: UID         = $(id -u)"
-#echo "I: DIST        = ${DIST}"
-#echo "I: SCHROOT_CMD = ${SCHROOT_CMD}"
-#echo "I: ----------------------------"
+case "$1" in
+  '')
+    DIST="unstable"
+    ;;
+  u)
+    DIST="unstable"
+    shift
+    ;;
+  t)
+    DIST="testing"
+    shift
+    ;;
+  s)
+    DIST="stable"
+    shift
+    ;;
+  o)
+    DIST="oldstable"
+    shift
+    ;;
+  oo)
+    DIST="oldoldstable"
+    shift
+    ;;
+  unstable|testing|stable|oldstable|oldoldstable)
+    DIST="${1}"
+    shift
+    ;;
+  sid|bookworm|bullseye|buster|strech)
+    DIST="${1}"
+    shift
+    ;;
+  *)
+    echo "W: unknown distribution ${1}"
+    _help
+    exit 0
+    ;;
+esac
 
-case "$SCHROOT_CMD" in
-  in*)
-    _su "$SCHROOT_SHELL" "-i" "$DIST"
+if [ -n "$1" ]; then
+  CONFIG="${1}"
+else
+  CONFIG="desktop"
+fi
+
+case "$COMMAND_MODE" in
+  co*) # config
+    _su "$THIS_COMMAND" "-c" "$CONFIG"
+    _config
+    exit 0
+    ;;
+  in*) # init
+    _su "$THIS_COMMAND" "-i" "$DIST" "$CONFIG"
     _init
     _upgrade
     _prep
     exit 0
     ;;
-  pr*)
-    _su "$SCHROOT_SHELL" "-p" "$DIST"
+  pr*) # prep
+    _su "$THIS_COMMAND" "-p" "$DIST" "$CONFIG"
     _upgrade
     _prep
     exit 0
     ;;
-  up*)
-    _su "$SCHROOT_SHELL" "-u" "$DIST"
+  up*) # upgrade
+    _su "$THIS_COMMAND" "-u" "$DIST" "$CONFIG"
     _upgrade
     exit 0
     ;;
-  sh*)
+  sh*) # shell
     trap _noxhost 0
     _distsh
     ;;
 esac
+
