Refine messages
Aggregate configurable

Signed-off-by: Osamu Aoki <osamu@debian.org>

diff --git a/secret-folder b/secret-folder
--- a/secret-folder
+++ b/secret-folder
@@ -1,16 +1,36 @@
 #!/bin/sh -e
 # vim:se sw=2 ts=2 sts=2 et ai tw=78:
-### VARIABLES ###
+#
+# This script creates a filesystem image file in which LUKS encrypted data is
+# stored.  This is aimed to store sensitive data securely with remote host
+# service rsync.net using rsync.  For other cloud services, rsync may need to
+# be replaced with rclone command.
+#
+# To recover the last data, use rsync as:
+# $ mkdir -p path/to
+# $ cd path/to
+# $ rsync -a de1234@de1234.rsync.net:rsync .
+#
+# ... or specifically for this disk image file with
+# $ rsync -a de1234@de1234.rsync.net:rsync/secret.img .
+#
+# To recover the older backup data, use rsync as:
+# $ rsync -a de1234@de1234.rsync.net:.zfs/snapshot/daily_2022-01-01 .
+#
+# For list of available older backups
+# $ ssh de1234@de1234.rsync.net ls -lsa .zfs/snapshot
+#
+# All these require us to set up ssh keys.
+#   https://www.rsync.net/resources/howto/ssh_keys.html
+#
+### VARIABLES (Edit this to adopt to the system) ###
 HOME="$(eval echo ~)"
 # disk image path
 PATH_DISK="$HOME/rsync/secret.img"
 # device mapper target name
 DM_TARGET=secret
 # mount path
-PATH_MNT="$HOME/secret"
-# device mapper target name
-DM_TARGET="${PATH_DISK##*/}"
-DM_TARGET="${DM_TARGET%%.*}"
+PATH_MNT="$HOME/$DM_TARGET"
 # set mode
 ECHO="echo"
 TSLEEP="0"
@@ -19,6 +39,38 @@ MOUNT="0"
 UPDATE="0"
 KEEP="0"
 SIZE_DISK="16G"
+# Multi line string
+TARGET_FILES="# Edit this to adopt to the system
+# Files to backup
+.bash_logout
+.bashrc
+.profile
+.bash_aliases
+.bash_fzf_completion
+.bash_fzf_keybindings
+.bashrc
+.benrc
+.caffrc
+.debrc
+.devscripts
+.gbp.conf
+.gitconfig
+.quiltrc-dpkg
+.reportbugrc
+.sbuildrc
+.shellcheckrc
+.config/black
+.config/flake8
+.config/pylintrc
+# directories to backup
+Documents
+bin
+.ssh
+.gnupg
+.config/autostart
+.config/systemd/user
+.local/share/keyrings
+"
 while [ -n "$1" ]; do
   case "$1" in
     new)
@@ -73,48 +125,51 @@ new_secret () {
   echo "I: create LUKS in $PATH_DISK" >&2
   secret-tool lookup LUKS "$PATH_DISK" | \
     cryptsetup luksFormat "$PATH_DISK" -
-  echo "I: open LUKS as $DM_TARGET" >&2
+  echo "I: open LUKS as /dev/mapper/$DM_TARGET" >&2
   secret-tool lookup LUKS "$PATH_DISK" | \
     sudo cryptsetup open "$PATH_DISK" "$DM_TARGET" --type luks
   echo "I: create btrfs in /dev/mapper/$DM_TARGET" >&2
   sudo mkfs.btrfs "/dev/mapper/$DM_TARGET"
-  mkdir -p "$PATH_MNT"
-  echo "I: mount $DM_TARGET on $PATH_MNT"
+  echo "I: mount /dev/mapper/$DM_TARGET on $PATH_MNT"
   sudo mount "/dev/mapper/$DM_TARGET" "$PATH_MNT"
-  echo "I: set UID:GID=1000:1000 for $PATH_MNT" >&2
+  echo "I: set $PATH_MNT to UID:GID=1000:1000" >&2
   sudo chown "1000:1000" "$PATH_MNT"
-  echo "!!! Don't write into ~/secret/ manually                 !!!" >  ~/secret/DO_NOT_WRITE_IN_MANUALLY
-  echo "!!! This should be accessed only by ~/bin/secret-folder !!!" >> ~/secret/DO_NOT_WRITE_IN_MANUALLY
+  {
+    echo "!!! Don't write into ~/secret/ manually                 !!!"
+    echo "!!! This should be accessed only by ~/bin/secret-folder !!!"
+  } > "$PATH_MNT/DO_NOT_WRITE_IN_MANUALLY"
 }
 
 check_secret () {
   if [ ! -e "$PATH_DISK" ]; then
-    $ECHO "disk image missing: $PATH_DISK"
-    $ECHO "create disk image using ~/bin/luks-image script interactively"
+    $ECHO "E: disk image missing: $PATH_DISK"
+    $ECHO "I: create disk image interactively as: ${0##*/} new [size]"
     exit 1
   fi
-  if [ ! -e "$PATH_MNT" ]; then
-    $ECHO "E: mount point path missing: $PATH_MNT"
-    exit 1
-  fi
-  # wait for 120s if run by systemd start up
+  # wait for 120s if run by systemd start up, otherwise no wait
   sleep $TSLEEP
 }
 
 mount_secret () {
   # let's mount
   if mount|grep -e "$PATH_MNT" >/dev/null; then
-    $ECHO "skipping to mount LUKS disk image $PATH_DISK on $PATH_MNT (already mounted)"
+    $ECHO "I: skip mounting:   /dev/mapper/$DM_TARGET on $PATH_MNT"
+    $ECHO "I: already mounted: $(mount|grep -e "$PATH_MNT"|sed 's/type.*$//')"
   else
-    $ECHO "unlock LUKS disk image $PATH_DISK as $DM_TARGET"
+    $ECHO "I: unlock LUKS disk image $PATH_DISK as /dev/mapper/$DM_TARGET"
     secret-tool lookup LUKS "$PATH_DISK" | \
       sudo cryptsetup open "$PATH_DISK" "$DM_TARGET" --type luks
-    $ECHO "mount $DM_TARGET on $PATH_MNT"
+    $ECHO "I: mount /dev/mapper/$DM_TARGET on $PATH_MNT"
     sudo mount "/dev/mapper/$DM_TARGET" "$PATH_MNT"
   fi
+  $ECHO "I: disk image usage (size used avail use%): $(df -h "$PATH_MNT" \
+    | grep "$PATH_MNT" \
+    | sed -e 's/\s\s*/ /g' \
+    | cut -d' ' -f 2-5)"
 }
 
 backup_secret () {
+$ECHO "I: back up to $PATH_MNT"
 while read -r F ; do
   D="$(dirname "$F")"
   if [ "$D" = "." ]; then
@@ -124,12 +179,12 @@ while read -r F ; do
   fi
   if [ -f "$F" ]; then
     if [ -n "$D" ]; then
-      mkdir -p "$HOME/secret/$D"
+      mkdir -p "$PATH_MNT/$D"
     fi
-    rsync -a "$HOME/$F" "$HOME/secret/$D"
+    rsync -a "$HOME/$F" "$PATH_MNT/$D"
   elif [ -d "$F" ]; then
-    mkdir -p "$HOME/secret/$F"
-    rsync -ax --del "$HOME/$F/" "$HOME/secret/$F"
+    mkdir -p "$PATH_MNT/$F"
+    rsync -ax --del "$HOME/$F/" "$PATH_MNT/$F"
   else
     $ECHO "broken ${0##*/}: $F non-existing"
   fi
@@ -144,9 +199,10 @@ unmount_secret () {
 
 ### MAIN ###
 
-# mount ~/secret
 cd "$HOME"
+mkdir -p "$PATH_MNT"
 
+# mount ~/secret
 if [ "$NEW" = "1" ]; then
   new_secret
 fi
@@ -157,38 +213,7 @@ fi
 # backup secret files into ~/secret
 
 if [ "$UPDATE" = "1" ]; then
-  { grep -v "^#" << EOF
-# Files to backup
-.bash_logout
-.bashrc
-.profile
-.bash_aliases
-.bash_fzf_completion
-.bash_fzf_keybindings
-.bashrc
-.benrc
-.caffrc
-.debrc
-.devscripts
-.gbp.conf
-.gitconfig
-.quiltrc-dpkg
-.reportbugrc
-.sbuildrc
-.shellcheckrc
-.config/black
-.config/flake8
-.config/pylintrc
-# directories to backup
-Documents
-bin
-.ssh
-.gnupg
-.config/autostart
-.config/systemd/user
-.local/share/keyrings
-EOF
-  } | backup_secret
+  { echo "$TARGET_FILES" | grep -v "^#" - } | backup_secret
 fi
 
 if [ "$KEEP" != "1" ]; then
